### ISSUE TITLE
Keep the dictionary file updated

### ISSUE THREAD

**Issue by crayxt** [TLemur/hunspell-kk#1]
I shared a Google Docs spreadsheet with you, do not forget to regularly pull new data from it. Keep this open.

**Comment by TLemur** [comment]
Updated to today's revision. Please reopen when some number of new changes is accumulated

**Comment by crayxt** [comment]
Updated, now at 59%.

**Comment by crayxt** [comment]
Closing since dictionary being gradually moved to lists directory.

**Comment by ildar** [comment]
Прошу пояснить:
Словарь мигрировал в файлы папки `lists/` (по последнему сообщению Бауыржана).
Тогда:
1. файл `kk_KZ.dic` не актуален? Его надо удалять из репозитария? Впрочем тоже не похоже, т.к. в `lists/` явно не все буквы.
2. Как тогда собирать реальный словарь из этих файлов?

**Comment by TLemur** [comment]
Словарь не мигрировал, мигрировал список слов для работы по уточнению частей речи.
1. Актуален и будет актуален, пока не закончим работы по списку слов. Скоро добавлю все буквы.
2. Никак.
