### ISSUE TITLE
Әріп - әрпіне

### ISSUE THREAD

**Issue by crayxt** [TLemur/hunspell-kk#5]
Правильный вариант Әріп - әрпіне.
А словарь предлагает әріпіне.

**Comment by TLemur** [comment]
Полное спряжение дай пожалуйста

**Comment by crayxt** [comment]
А І Б Т Ж Ш К

(полиция;полицияның;полицияға;полицияны;полицияда;полициядан;полициямен)

вообще то по моему есть два варианта написания
Третье лицо: әрібі,әрібінің,әрібіне,әрібін,әрібінде,әрібінен,әрібімен
а также
әрпі, әрпінің, әрпіне, әрпін, әрпінде, әрпінен, (әрпімен?)

**Comment by TLemur** [comment]
Half fixed by today's commits
