### ISSUE TITLE
құқығымызды

### ISSUE THREAD

**Issue by crayxt** [TLemur/hunspell-kk#8]
это правильный вариант. А словарь предлагает құқықымызды

**Comment by crayxt** [comment]
Также аумағының, а словарь предлагает аумақының

**Comment by crayxt** [comment]
также тұтастығын, а словарь предлагает тұтастықын

**Comment by TLemur** [comment]
Closed in 3c257f93e8422ac57fa14aeadc40c7e6edff7789
